### ISSUE TITLE
jasmine-json-stream-reporter problem

### ISSUE THREAD

**Issue by Ruff9** [jasmine/gulp-jasmine-browser#43]
I'm trying to use gulp-jasmine-browser for the first time, I must be missing something. The specs are running smoothly in my navigator, but I need them in command line for my CI.

When I launch  the gulp task in my console, I get this result :

```
[15:44:55] Using gulpfile ~/dev/atletic-run-vma/gulpfile.js
[15:44:55] Starting 'jasmine'...
[15:44:55] Jasmine server listening on port 8000
/Users/macbookairdls/dev/atletic-run-vma/node_modules/jasmine-json-stream-reporter/to-reporter.js:50
    Object.keys(events).find(function (key) {
                        ^
TypeError: undefined is not a function
  at DestroyableTransform._transform (/Users/macbookairdls/dev/atletic-run-vma/node_modules/jasmine-json-stream-reporter/to-reporter.js:50:25)
  at DestroyableTransform.Transform._read (/Users/macbookairdls/dev/atletic-run-vma/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
  at DestroyableTransform.Transform._write (/Users/macbookairdls/dev/atletic-run-vma/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
  at doWrite (/Users/macbookairdls/dev/atletic-run-vma/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:347:64)
  at writeOrBuffer (/Users/macbookairdls/dev/atletic-run-vma/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:336:5)
  at DestroyableTransform.Writable.write (/Users/macbookairdls/dev/atletic-run-vma/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:274:11)
  at Stream.ondata (stream.js:51:26)
  at Stream.emit (events.js:107:17)
  at drain (/Users/macbookairdls/dev/atletic-run-vma/node_modules/through/index.js:36:16)
  at Stream.stream.queue.stream.push (/Users/macbookairdls/dev/atletic-run-vma/node_modules/through/index.js:45:5)
  at Stream.stream.write (/Users/macbookairdls/dev/atletic-run-vma/node_modules/through/index.js:26:11)
  at DestroyableTransform.ondata (/Users/macbookairdls/dev/atletic-run-vma/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:546:20)
  at DestroyableTransform.emit (events.js:107:17)
  at readableAddChunk (/Users/macbookairdls/dev/atletic-run-vma/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:217:18)
  at DestroyableTransform.Readable.push (/Users/macbookairdls/dev/atletic-run-vma/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:176:10)
  at DestroyableTransform.Transform.push (/Users/macbookairdls/dev/atletic-run-vma/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:123:32)
  at push (/Users/macbookairdls/dev/atletic-run-vma/node_modules/split2/index.js:52:10)
  at DestroyableTransform.transform [as _transform] (/Users/macbookairdls/dev/atletic-run-vma/node_modules/split2/index.js:33:5)
  at DestroyableTransform.Transform._read (/Users/macbookairdls/dev/atletic-run-vma/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
  at DestroyableTransform.Transform._write (/Users/macbookairdls/dev/atletic-run-vma/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
  at doWrite (/Users/macbookairdls/dev/atletic-run-vma/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:347:64)
  at writeOrBuffer (/Users/macbookairdls/dev/atletic-run-vma/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:336:5)
  at DestroyableTransform.Writable.write (/Users/macbookairdls/dev/atletic-run-vma/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:274:11)
  at Socket.ondata (_stream_readable.js:540:20)
  at Socket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at Socket.Readable.push (_stream_readable.js:126:10)
  at Pipe.onread (net.js:538:20)
```

my gulpfile:

```
gulp.task('jasmine', function() {
  return gulp.src([
    './www/scripts/vendor.js',
    './www/scripts/jasmine-jquery.js',
    './www/scripts/template.js',
    './www/scripts/params.js',
    './www/scripts/app.js',
    './specs/spec.js'
    ]).pipe(jasmineBrowser.specRunner({console: true}))
    .pipe(jasmineBrowser.headless());
});
```

**Comment by rdy** [comment]
Hmm, which version of node are you running? It looks like you might have run into a transpiling issue where array doesn't have a find function.
