### ISSUE TITLE
Issue while Trying to run Foreman

### ISSUE THREAD

**Issue by dan-ator** [jasmine/gulp-jasmine-browser#55]
I am getting this error message:

```
/node_modules/gulp-jasmine-browser/node_modules/multipipe/index.js:6
const { PassThrough, Readable } = require('stream')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/dalexander1/Loglio/loglio/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/dalexander1/Loglio/loglio/node_modules/gulp-jasmine-browser/lib/headless.js:76:18)
    at Module._compile (module.js:413:34)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/dalexander1/Loglio/loglio/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/dalexander1/Loglio/loglio/node_modules/gulp-jasmine-browser/index.js:8:17)
    at Module._compile (module.js:413:34)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/dalexander1/Loglio/loglio/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```
This is for gulp-jasmine-browser 2.0.4, which is installed by pui-react-tools 3.2.2. 

Is this some known issue I am missing?

**Comment by sgravrock** [comment]
From the error message it looks like you might be using a version of Node that's too old to support the object destructuring syntax used by the `multipipe` module. I suggest at least version 6, since [that's what the Travis tests run against](https://github.com/jasmine/gulp-jasmine-browser/blob/659cbae4959a0a178b136d9d4792c48cfd27f500/.travis.yml#L3-L4).

**Comment by rdy** [comment]
You can upgrade node or you can try to use Babel to polyfill the lacking support in your version of node. It looks like your version of node doesn’t support destructuring.
